<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="WarpToolkit.WinForms" />
	<PackageReference Include="WarpToolkit.WinForms.Specialized" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="WarpToolkit.Desktop.Async" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DebugListener\DebugMessageListener.cs">
      <SubType>Component</SubType>
    </Compile>
  </ItemGroup>

</Project>
