<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.22000.0</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" />
		<PackageReference Include="WarpToolkit.WinForms" />
		<PackageReference Include="WarpToolkit.WinForms.AppServices" />
		<PackageReference Include="WarpToolkit.WinForms.Extensions" />
		<PackageReference Include="WarpToolkit.WinForms.Specialized" />
		<PackageReference Include="Microsoft.VisualStudio.Setup.Configuration.Interop" />
	</ItemGroup>
</Project>
