<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net4.8</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	<langVersion>12.0</langVersion>
	<ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

</Project>