<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

	<!-- Define the version as a property -->
	<WarpToolkitVersion>0.9.323-preview.gb01532b307</WarpToolkitVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.6.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="3.14.2075" />
    <PackageVersion Include="NuGet.Versioning" Version="7.6.0" />
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />

	  <!-- Define your package versions here -->
    <PackageVersion Include="WarpToolkit.ComponentModel" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.Desktop.AppServices" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.Desktop.Async" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms.AppServices" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms.Async" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms.Extensions" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms.Specialized" Version="$(WarpToolkitVersion)" />
  </ItemGroup>
</Project>
