<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

	<!-- Define the version as a property -->
	<WarpToolkitVersion>0.7.25-preview.gb43a5f8ece</WarpToolkitVersion>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.14.0" />
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.0-preview-25107-01" />
    <PackageVersion Include="Microsoft.VisualStudio.Setup.Configuration.Interop" Version="3.13.2069" />
    <PackageVersion Include="NuGet.Versioning" Version="6.13.2" />
    <PackageVersion Include="Octokit" Version="14.0.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.0" />

	  <!-- Define your package versions here -->
    <PackageVersion Include="WarpToolkit.Desktop.Async" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms.AppServices" Version="$(WarpToolkitVersion)" />
    <PackageVersion Include="WarpToolkit.WinForms.Tooling" Version="$(WarpToolkitVersion)" />
  </ItemGroup>
</Project>
